### ISSUE TITLE
Add automatic currency conversion

### ISSUE THREAD

**Issue by sisou** [nimiq/woocommerce-gateway-nimiq#1]
Conversion data should be retrieved from an open API, such as Coinmarketcap or others. The plugin can also allow closed conversion services by enabling the user to input their API-access-token.

Additionally, the plugin can then also make use of the `AccountsClient.checkout()`'s `validityDuration` parameter to lock the conversion rate for a limited time only.

**Comment by Eligioo** [comment]
FYI, CMC has now different pricing plans for their API and require an access token as well.

**Comment by riptl** [comment]
NimiqX provides nice price data

**Comment by danimoh** [comment]
Also the coingecko api is free. That's also the one that https://nimiq.com/en/#exchanges uses
