### ISSUE TITLE
After payment redirect to Checkout page again

### ISSUE THREAD

**Issue by Eligioo** [nimiq/woocommerce-gateway-nimiq#10]
Within the settings page of the Woocommerce Nimiq Gateway plugin, I set the behavior to Redirect rather than Popup. Once I want to checkout with Nimiq, I click on Pay for Order.

The first thing that happens it that the page will reload (also happens when behaviour is Popup). I'm still on the Checkout page of Woocommerce rather than being redirected to the Keyguard. I click on Pay for Order **again**, I'm being redirected to the Keyguard. Once I passed everyting on the Keyguard, then I will be redirected to Checkout page **again** rather than the Confirmation page showing the details of your order.

The order on the backend has been created on Woocommerce but the status will always be Pending payment. Although the transaction actually has happened on the blockchain.

If I change Behaviour to Popup. I still have to click on Pay for Order twice but on the backend the order status will change to On hold and eventually to Processing and I will get redirected correctly to the Order status page after the Keyguard is closed.

Scenario to reproduce: the sender and receiver are both on the same Keyguard.

**Comment by Eligioo** [comment]
After going to the process again I noticed at payout that the Nimiq flow is that you:

1. Create the order
2. Pay for the order
3. Go to the Keyguard.

Normally you would directy go to the website of the payment processor. Not creating the order first and then pay for it. Still this doesn't solve the issue that when Behavior is Redirect, you will go back to the Checkout page rather than the Order detail page with the receipt.

**Comment by sisou** [comment]
Hi. What theme are you running? What woocommerce version?

**Comment by Eligioo** [comment]
Hi @sisou 
Just the default Twenty Nineteen wordpress theme.
Woocommerce: Version 3.5.4
Wordpress: 5.0.3

**Comment by sisou** [comment]
I created issues #11 and #12, which I believe are the underlying issues you are experiencing.

This plugin is currently only made for the Storefront theme, and is not tested with any other theme. Additionally, no errors are displayed when returning from the Keyguard, so you don't even know what went wrong.

Thanks for reporting! :+1:

**Comment by Eligioo** [comment]
@sisou  No problem. As you were creating the new issues #11 and #12  I was recording a Loom showing what's happening. Still can share it: https://www.useloom.com/share/4b9bc6335da74206aa9b5ee3564aa5c7
