### ISSUE TITLE
Add JSON-RPC as a validation service

### ISSUE THREAD

**Issue by sisou** [nimiq/woocommerce-gateway-nimiq#3]
Configuring a JSON-RPC service to use for validation requires the user to input the connection info (IP/URL & port, eventually authentication parameters).

[Instructions for adding a new validation service](https://github.com/nimiq/woocommerce-gateway-nimiq#adding-a-new-validation-service)

**Comment by riptl** [comment]
I'm on it 😄

**Comment by sisou** [comment]
Fixed by #5.
