### ISSUE TITLE
When an order expired before the user selected a currency, he can not create a new offer

### ISSUE THREAD

**Issue by danimoh** [nimiq/woocommerce-gateway-nimiq#32]
When an order expired before the user selected a currency, he can not create a new offer when going back to the shop (either via `Back to Shop` button on the expiration screen or `Cancel Payment` button at the bottom of the page) and clicking the `Create Order` button again.
When a currency was selected before the expiry this is working though.
I don't know whether this is an issue of the plugin or the integration in the shop.

**Comment by sisou** [comment]
How long was the quote expired for already, or rather how long after the order was first created did you try to generate a new quote?

**Comment by danimoh** [comment]
I think immediately and then also at later points in time.

**Comment by sisou** [comment]
I cannot reproduce that.

What I did:
- Created an order in the KH shop
- Selected Nimiq Crypto Checkout and openend the popup
- Did nothing for 15 minutes
- Clicked "Back to shop"
- Clicked "Create order" again and got a new quote, new popup, and new 15 min validity

Orders are cancelled, and can thus not be paid anymore, in two scenarios:
* by the WooCommerce system roughly 1 hour after they were created (this is a setting in WooCommerce for how long inventory is held for unpaid orders, currently set to 60 min in KH shop), but only when the shop is used after that time (the cancellation action seems to be a hook that only runs when the shop code runs).

* 2 hours after the order was created **and** a currency was selected (the currency selection makes it a _monitored order_), as this is a scheduled action that runs every 5 minutes (as currently configured) to cancel monitored orders after no tx has been found after the "Mempool wait duration" setting, currently set to 120 min.

Let's have a call about the specifics of this, or describe how to reproduce this problem.

**Comment by danimoh** [comment]
This is fixed now.
