### ISSUE TITLE
Allow configuring JSON-RPC authentication

### ISSUE THREAD

**Issue by sisou** [nimiq/woocommerce-gateway-nimiq#8]
The JSON-RPC server can be configured to require username:password authentication. The server checks the `authorization` header for this info. Thus the plugin should be able to send this header when configured to do so.

Details about the validation here: https://github.com/nimiq-network/core/blob/master/clients/nodejs/modules/JsonRpcServer.js#L164

**Comment by riptl** [comment]
Solved in #9
